title: 예슬이 블로그
email: yeseal0628@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  이것저것 개발 관련 이야기가 올라옵니다. 사실 개발 말고 디자인, 기획관련해서도 쓰고싶은 글이 기록됩니다. 고로 뻘소리도 많을 예정.
baseurl: "/my-blog" # the subpath of your site, e.g. /blog
url: "https://yeseuljeong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username: jekyll

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/page/:num/"

sass:
  style: compressed
  sass_dir: _sass
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
